# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - App-TesisMaestria

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
   contents: read   
   
jobs:
  build:
    runs-on: ubuntu-latest
    #permissions:
     # contents: read
     # packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java version
        uses: actions/setup-java@v3.0.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          #settings-path: ${{ github.workspace }} # location for the settings.xml file

      #- name: Setup Gradle
      #  uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0
      
     # - name: otorgar permisos para gradle
     #   run: chmod +x ./gradlew
        
      - name: Build with Gradle
        #run: ./gradlew build --scan --no-daemon
        run: gradle build
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
              
      - name: 'Log into Azure using github secret AZURE_CREDENTIALS'
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: Azure/webapps-deploy@v3
        with:
          app-name: 'App-TesisMaestria'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
          #package: '/home/runner/work/tesismaestriaautonoma/tesismaestriaautonoma/build/libs/data-0.0.1-SNAPSHOT.jar'
          #package: '/home/runner/work/tesismaestriaautonoma/tesismaestriaautonoma/java-app/data-0.0.1-SNAPSHOT.jar'
